"""Typed raster contracts and explicit image backend adapters."""

from .contour_model import (
    CONTOUR_APPROXIMATION_MODE,
    CONTOUR_RETRIEVAL_MODE,
    MAX_CONTOUR_CANDIDATES,
    MAX_CONTOUR_EDGE_PIXELS,
    MAX_TOTAL_CONTOUR_POINTS,
    ContourCandidate,
    ContourExtractionError,
    ContourExtractionResult,
    ContourFailureCode,
    PixelPoint,
    contour_bounding_box,
    signed_shoelace_area2,
)
from .edge_detection import detect_canny_edges, detect_threshold_boundary
from .edge_model import (
    BoundaryConnectivity,
    CannyParameters,
    EdgeAlgorithm,
    EdgeDetectionError,
    EdgeDetectionResult,
    EdgeFailureCode,
    EdgeParameters,
    ThresholdBoundaryParameters,
)
from .model import (
    MAX_DECODED_IMAGE_PIXELS,
    MAX_ENCODED_IMAGE_BYTES,
    DecodedImage,
    DenoiseMode,
    ImageDecodeProvenance,
    ImageFailureCode,
    ImageFormat,
    ImageInputError,
    ImagePreprocessingOptions,
    ImagePreprocessingProvenance,
    ImagePreprocessingResult,
    RasterImage,
    RasterStage,
)
from .opencv_contours import extract_external_contours
from .pillow_backend import (
    autocontrast_grayscale,
    decode_image_bytes,
    decode_local_image,
    export_raster_png,
    median_denoise,
    threshold_grayscale,
)
from .skeleton_adjacency import raw_adjacency
from .skeleton_graph import build_skeleton_graph
from .skeleton_graph_model import (
    MAX_SKELETON_GRAPH_FOREGROUND_PIXELS,
    MAX_SKELETON_GRAPH_JSON_BYTES,
    MAX_SKELETON_GRAPH_RECORDS,
    SKELETON_GRAPH_ADJACENCY_POLICY,
    SKELETON_GRAPH_BUILDER,
    SKELETON_GRAPH_SCHEMA,
    SkeletonGraphComponent,
    SkeletonGraphEdge,
    SkeletonGraphError,
    SkeletonGraphFailureCode,
    SkeletonGraphNode,
    SkeletonGraphResult,
    SkeletonNodeKind,
)
from .skeleton_model import (
    MAX_SKELETON_FOREGROUND_PIXELS,
    SkeletonAlgorithm,
    SkeletonFailureCode,
    SkeletonizationError,
    SkeletonizationResult,
)
from .skimage_skeleton import skeletonize_binary

__all__ = [
    "CONTOUR_APPROXIMATION_MODE",
    "CONTOUR_RETRIEVAL_MODE",
    "MAX_CONTOUR_CANDIDATES",
    "MAX_CONTOUR_EDGE_PIXELS",
    "MAX_DECODED_IMAGE_PIXELS",
    "MAX_ENCODED_IMAGE_BYTES",
    "MAX_SKELETON_FOREGROUND_PIXELS",
    "MAX_SKELETON_GRAPH_FOREGROUND_PIXELS",
    "MAX_SKELETON_GRAPH_JSON_BYTES",
    "MAX_SKELETON_GRAPH_RECORDS",
    "MAX_TOTAL_CONTOUR_POINTS",
    "SKELETON_GRAPH_ADJACENCY_POLICY",
    "SKELETON_GRAPH_BUILDER",
    "SKELETON_GRAPH_SCHEMA",
    "BoundaryConnectivity",
    "CannyParameters",
    "ContourCandidate",
    "ContourExtractionError",
    "ContourExtractionResult",
    "ContourFailureCode",
    "DecodedImage",
    "DenoiseMode",
    "EdgeAlgorithm",
    "EdgeDetectionError",
    "EdgeDetectionResult",
    "EdgeFailureCode",
    "EdgeParameters",
    "ImageDecodeProvenance",
    "ImageFailureCode",
    "ImageFormat",
    "ImageInputError",
    "ImagePreprocessingOptions",
    "ImagePreprocessingProvenance",
    "ImagePreprocessingResult",
    "PixelPoint",
    "RasterImage",
    "RasterStage",
    "SkeletonAlgorithm",
    "SkeletonFailureCode",
    "SkeletonGraphComponent",
    "SkeletonGraphEdge",
    "SkeletonGraphError",
    "SkeletonGraphFailureCode",
    "SkeletonGraphNode",
    "SkeletonGraphResult",
    "SkeletonNodeKind",
    "SkeletonizationError",
    "SkeletonizationResult",
    "ThresholdBoundaryParameters",
    "autocontrast_grayscale",
    "build_skeleton_graph",
    "contour_bounding_box",
    "decode_image_bytes",
    "decode_local_image",
    "detect_canny_edges",
    "detect_threshold_boundary",
    "export_raster_png",
    "extract_external_contours",
    "median_denoise",
    "raw_adjacency",
    "signed_shoelace_area2",
    "skeletonize_binary",
    "threshold_grayscale",
]
