"""Typed raster contracts and explicit image backend adapters."""

from .edge_detection import detect_canny_edges, detect_threshold_boundary
from .edge_model import (
    BoundaryConnectivity,
    CannyParameters,
    EdgeAlgorithm,
    EdgeDetectionError,
    EdgeDetectionResult,
    EdgeFailureCode,
    EdgeParameters,
    ThresholdBoundaryParameters,
)
from .model import (
    MAX_DECODED_IMAGE_PIXELS,
    MAX_ENCODED_IMAGE_BYTES,
    DecodedImage,
    DenoiseMode,
    ImageDecodeProvenance,
    ImageFailureCode,
    ImageFormat,
    ImageInputError,
    ImagePreprocessingOptions,
    ImagePreprocessingProvenance,
    ImagePreprocessingResult,
    RasterImage,
    RasterStage,
)
from .pillow_backend import (
    autocontrast_grayscale,
    decode_image_bytes,
    decode_local_image,
    export_raster_png,
    median_denoise,
    threshold_grayscale,
)

__all__ = [
    "MAX_DECODED_IMAGE_PIXELS",
    "MAX_ENCODED_IMAGE_BYTES",
    "BoundaryConnectivity",
    "CannyParameters",
    "DecodedImage",
    "DenoiseMode",
    "EdgeAlgorithm",
    "EdgeDetectionError",
    "EdgeDetectionResult",
    "EdgeFailureCode",
    "EdgeParameters",
    "ImageDecodeProvenance",
    "ImageFailureCode",
    "ImageFormat",
    "ImageInputError",
    "ImagePreprocessingOptions",
    "ImagePreprocessingProvenance",
    "ImagePreprocessingResult",
    "RasterImage",
    "RasterStage",
    "ThresholdBoundaryParameters",
    "autocontrast_grayscale",
    "decode_image_bytes",
    "decode_local_image",
    "detect_canny_edges",
    "detect_threshold_boundary",
    "export_raster_png",
    "median_denoise",
    "threshold_grayscale",
]
