"""Application use cases for Fourier Sketch."""

from fourier_sketch.math import ResamplingMethod

from .adaptive_sampling import (
    AdaptiveSamplingComparison,
    AdaptiveSamplingConfig,
    compare_adaptive_sampling,
)
from .curve_simplification import (
    CurveSimplificationComparison,
    CurveSimplificationConfig,
    compare_curve_simplification,
)
from .diagnostic_epicycles import (
    EpicycleFrame,
    EpicycleTimeline,
    RenderVisibility,
    TimelineState,
    validate_timeline_speed,
)
from .discontinuous_fourier import (
    DiscontinuitySpectrumComparison,
    DiscontinuousFourierResult,
    DiscontinuousMode,
    ForcedRouteFourierComparison,
    analyze_discontinuity_vs_continuous,
    build_discontinuous_fourier,
    compare_discontinuous_with_forced_route,
)
from .dominant_contour import (
    DEFAULT_CONTOUR_HARMONICS,
    DEFAULT_CONTOUR_SAMPLES,
    ImageContourTimelineResult,
    ImageNoContourResult,
    build_dominant_contour_timeline,
)
from .edge_detection import detect_preprocessed_edges, export_edge_result
from .exporting import (
    EXPORT_SCHEMA_VERSION,
    MAX_GIF_FRAME_DURATION_MS,
    MAX_GIF_FRAMES,
    MIN_GIF_FRAME_DURATION_MS,
    MIN_GIF_FRAMES,
    AnimationExportPlan,
    ExportCancelled,
    ExportCapability,
    ExportFormat,
    ExportUnavailable,
    atomic_publish_bytes,
    export_coefficient_data,
    export_curve_data,
    iter_animation_frames,
    mp4_capability,
)
from .fft2_image import build_fft2_image
from .forced_route import (
    DEFAULT_ROUTE_HARMONICS,
    DEFAULT_ROUTE_SAMPLES,
    ForcedRouteOptimizationComparison,
    LocalForcedRouteResult,
    build_local_forced_route,
    compare_local_forced_routes,
)
from .freehand import (
    DEFAULT_FREEHAND_HARMONICS,
    DEFAULT_FREEHAND_SAMPLES,
    MAX_CAPTURE_POINTS,
    CaptureState,
    FreehandCapture,
    FreehandCaptureSnapshot,
    FreehandCurveResult,
    build_freehand_timeline,
)
from .frequency_solo import FrequencySoloSession
from .harmonic_build_up import (
    DEFAULT_BUILD_UP_DWELL_SECONDS,
    MAX_BUILD_UP_DWELL_SECONDS,
    MIN_BUILD_UP_DWELL_SECONDS,
    BuildUpMetrics,
    BuildUpSnapshot,
    BuildUpState,
    HarmonicBuildUpSession,
)
from .image_mvp import (
    ImageMvpConfig,
    ImageMvpController,
    ImageMvpResult,
    ImageMvpSnapshot,
    ImageMvpState,
)
from .image_preprocessing import (
    export_preprocessing_result,
    preprocess_local_image,
    select_preprocessing_raster,
)
from .local_paths import LocalPathError, safe_display_basename, validate_local_path
from .piecewise_skeleton import LocalPiecewiseResult, build_local_piecewise
from .skeleton_graph import (
    LocalSkeletonGraphResult,
    build_local_skeleton_graph,
    export_skeleton_graph_json,
)
from .skeletonization import (
    LocalSkeletonResult,
    SkeletonConfig,
    SkeletonController,
    SkeletonSnapshot,
    SkeletonState,
    build_local_skeleton,
    export_local_skeleton,
)

__all__ = [
    "DEFAULT_BUILD_UP_DWELL_SECONDS",
    "DEFAULT_CONTOUR_HARMONICS",
    "DEFAULT_CONTOUR_SAMPLES",
    "DEFAULT_FREEHAND_HARMONICS",
    "DEFAULT_FREEHAND_SAMPLES",
    "DEFAULT_ROUTE_HARMONICS",
    "DEFAULT_ROUTE_SAMPLES",
    "EXPORT_SCHEMA_VERSION",
    "MAX_BUILD_UP_DWELL_SECONDS",
    "MAX_CAPTURE_POINTS",
    "MAX_GIF_FRAMES",
    "MAX_GIF_FRAME_DURATION_MS",
    "MIN_BUILD_UP_DWELL_SECONDS",
    "MIN_GIF_FRAMES",
    "MIN_GIF_FRAME_DURATION_MS",
    "AdaptiveSamplingComparison",
    "AdaptiveSamplingConfig",
    "AnimationExportPlan",
    "BuildUpMetrics",
    "BuildUpSnapshot",
    "BuildUpState",
    "CaptureState",
    "CurveSimplificationComparison",
    "CurveSimplificationConfig",
    "DiscontinuitySpectrumComparison",
    "DiscontinuousFourierResult",
    "DiscontinuousMode",
    "EpicycleFrame",
    "EpicycleTimeline",
    "ExportCancelled",
    "ExportCapability",
    "ExportFormat",
    "ExportUnavailable",
    "ForcedRouteFourierComparison",
    "ForcedRouteOptimizationComparison",
    "FreehandCapture",
    "FreehandCaptureSnapshot",
    "FreehandCurveResult",
    "FrequencySoloSession",
    "HarmonicBuildUpSession",
    "ImageContourTimelineResult",
    "ImageMvpConfig",
    "ImageMvpController",
    "ImageMvpResult",
    "ImageMvpSnapshot",
    "ImageMvpState",
    "ImageNoContourResult",
    "LocalForcedRouteResult",
    "LocalPathError",
    "LocalPiecewiseResult",
    "LocalSkeletonGraphResult",
    "LocalSkeletonResult",
    "RenderVisibility",
    "ResamplingMethod",
    "SkeletonConfig",
    "SkeletonController",
    "SkeletonSnapshot",
    "SkeletonState",
    "TimelineState",
    "analyze_discontinuity_vs_continuous",
    "atomic_publish_bytes",
    "build_discontinuous_fourier",
    "build_dominant_contour_timeline",
    "build_fft2_image",
    "build_freehand_timeline",
    "build_local_forced_route",
    "build_local_piecewise",
    "build_local_skeleton",
    "build_local_skeleton_graph",
    "compare_adaptive_sampling",
    "compare_curve_simplification",
    "compare_discontinuous_with_forced_route",
    "compare_local_forced_routes",
    "detect_preprocessed_edges",
    "export_coefficient_data",
    "export_curve_data",
    "export_edge_result",
    "export_local_skeleton",
    "export_preprocessing_result",
    "export_skeleton_graph_json",
    "iter_animation_frames",
    "mp4_capability",
    "preprocess_local_image",
    "safe_display_basename",
    "select_preprocessing_raster",
    "validate_local_path",
    "validate_timeline_speed",
]
